name: furconnect
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  go_router: ^14.6.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.4.0
  logger: ^2.5.0
  provider: ^6.1.2
  dropdown_search: ^6.0.2
  image_picker: ^1.1.2
  file_picker: ^8.3.1
  connectivity_plus: ^6.1.2
  image: ^4.5.2
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3




flutter:
  assets:
    - .env
    - assets/images/logo_furconnect.png
    - assets/images/background_login_copy.png
    - assets/images/placeholder/pet_placeholder.jpg
    - assets/images/placeholder/item_pet_placeholder.jpeg
    - assets/images/Login/pet1.jpg
    - assets/images/Login/pet2.jpg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 600
    - family: RobotoR
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  uses-material-design: true
